export default class FusionConstant {
  static ROUTE_NAME = 'ROUTE_NAME'
  static ROUTE_ARGUMENTS = 'ROUTE_ARGUMENTS'
  static INITIAL_ROUTE = '/'
  static FUSION_CHANNEL = 'fusion_channel'
  static EXTRA_BACKGROUND_MODE = 'background_mode'
  static EXTRA_BACKGROUND_COLOR = 'background_color'
  static FUSION_RESTORATION_HISTORY_KEY = 'history'
  static FUSION_RESTORATION_UNIQUE_ID_KEY = 'uniqueId'
  static TRANSPARENT_WINDOW = 'TRANSPARENT_WINDOW'
}