export default class FusionConstant {
  static ROUTE_NAME: string = 'ROUTE_NAME'
  static ROUTE_ARGS: string = 'ROUTE_ARGS'
  static INITIAL_ROUTE: string = '/'
  static FUSION_CHANNEL: string = 'fusion_channel'
  static EXTRA_BACKGROUND_MODE: string = 'background_mode'
  static EXTRA_BACKGROUND_COLOR: string = 'background_color'
  static FUSION_RESTORATION_HISTORY_KEY: string = 'history'
  static FUSION_RESTORATION_UNIQUE_ID_KEY: string = 'uniqueId'
}